src/meals/urls.py
from django.urls import path
from . import views

app_name = 'meals'

urlpatterns = [
    path('', views.meal_list,name='meal_list'),
    path('<slug:slug>', views.meal_detail, name='meal_detail'),
]


"""
Importación de módulos:
from django.urls import path: Importa la función path de Django, que se utiliza para definir rutas URL en tu aplicación.
from . import views: Importa el módulo de vistas (views.py) desde el directorio actual (.) de tu aplicación.
Definición del espacio de nombres de la aplicación:
app_name = 'meals': Define un espacio de nombres para las URL de tu aplicación. Esto es útil cuando tienes múltiples aplicaciones en tu proyecto Django y quieres evitar conflictos de nombres de URL.
Configuración de las URL:
urlpatterns: Es una lista de objetos de ruta URL que define las URL para tu aplicación.
path('', views.meal_list): Define una ruta URL vacía que apunta a la vista meal_list. Esto significa que cuando alguien visite la ruta base de tu aplicación (por ejemplo, http://tudominio.com/meals/), se mostrará la lista de comidas.
path('<slug:slug>', views.meal_detail, name='meal_detail'): Define una ruta URL con un parámetro dinámico slug. Este patrón de URL captura un slug único que identifica una comida específica. Por ejemplo, cuando alguien visite una URL como http://tudominio.com/meals/nombre-de-la-comida/, se llamará a la vista meal_detail para mostrar los detalles de esa comida. El parámetro name='meal_detail' asigna un nombre a esta ruta URL, lo que permite referenciarla de manera única en tus plantillas HTML usando el sistema de plantillas de Django.
"""

src/project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('meals/',include('meals.urls',namespace='meals')),
]



urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/meals/models.py
from django.db import models
from django.utils.text import slugify
# Create your models here.
class Meals(models.Model):
    name = models.CharField(max_length=50)
    description = models.TextField(max_length=500)
    category = models.ForeignKey('Category', on_delete=models.SET_NULL, null=True)
    people = models.IntegerField()
    price = models.DecimalField(max_digits=5, decimal_places=2)
    preparation_time = models.DecimalField(max_digits=5, decimal_places=2)
    imagen = models.ImageField(upload_to='meals/')
    slug = models.SlugField(blank=True, null=True)
    
    def save(self, *args, **kwargs):
        if not self.slug and self.name :
            self.slug = slugify(self.name)
        super(Meals, self).save(*args, **kwargs)

    class Meta:
        verbose_name='meal'
        verbose_name_plural='meals'
    

    def __str__(self):
        return self.name

class Category(models.Model):
    name = models.CharField(max_length=30)

    class Meta:
        verbose_name='category'
        verbose_name_plural='categories'
        
    def __str__(self):
        return self.name

"""
Importaciones:
from django.db import models: Importa la clase Model de Django, que es la base para definir modelos en Django.
from django.utils.text import slugify: Importa la función slugify de Django, que se utiliza para convertir cadenas de texto en slugs (es decir, versiones amigables para URL) al eliminar caracteres especiales y espacios y convertirlos en minúsculas.
Definición del modelo Meals:
class Meals(models.Model): Define una clase llamada Meals que hereda de models.Model, lo que indica que Meals es un modelo de Django.
Atributos del modelo:
name, description, people, price, preparation_time, imagen: Son campos del modelo Meals, cada uno representado por un tipo específico de campo de Django (por ejemplo, CharField, TextField, IntegerField, DecimalField, ImageField), que definen la estructura de datos de una comida.
slug: Es un campo SlugField que se utiliza para almacenar el slug de la comida. El campo slug es opcional (blank=True, null=True), lo que significa que puede estar vacío en la base de datos.
Método save:
Se define un método save personalizado para el modelo Meals. Este método se llama cada vez que se guarda una instancia del modelo en la base de datos.
Dentro del método save, se comprueba si el campo slug está vacío y si el campo name no está vacío. Si ambos son verdaderos, se genera un slug a partir del nombre de la comida utilizando la función slugify y se asigna al campo slug.
Luego, se llama al método save de la clase base (super(Meals, self).save(*args, **kwargs)) para guardar la instancia del modelo.
Clase Meta:
La clase Meta se utiliza para proporcionar metadatos adicionales al modelo.
verbose_name y verbose_name_plural: Define los nombres humanos legibles para el modelo en singular y plural, respectivamente.
Método __str__:
Se define un método __str__ para el modelo Meals, que devuelve una representación de cadena del objeto. En este caso, devuelve el nombre de la comida.
"""

src/meals/views.py
from django.shortcuts import render
from .models import Meals, Category
# Create your views here.

def meal_list(request):
    meal_list = Meals.objects.all() # lista de productos
    categories = Category.objects.all() 
    context = {
        'meal_list':meal_list,
        'categories': categories,
        }
    return render(request, 'Meals/list.html', context)

def meal_detail(request,slug):
    meal_detail = Meals.objects.get(slug=slug)
    context = {'meal_detail':meal_detail}
    return render(request, 'Meals/detail.html', context)


"""

Estas vistas están diseñadas para manejar las solicitudes relacionadas con las comidas en tu aplicación Django. Aquí hay una explicación detallada de cada una:

Vista meal_list:
Esta vista maneja las solicitudes para mostrar una lista de comidas.
Meals.objects.all() obtiene todos los objetos de Meals en la base de datos y los asigna a la variable meal_list.
Se crea un diccionario context que contiene la lista de comidas obtenidas.
Luego, la función render() toma la solicitud (request), la plantilla 'Meals/list.html', y el contexto (context) y renderiza la plantilla con el contexto proporcionado, devolviendo la página HTML resultante como respuesta.
Vista meal_detail:
Esta vista maneja las solicitudes para mostrar los detalles de una comida específica, identificada por su slug.
Toma un parámetro adicional slug, que representa el slug de la comida que se mostrará.
Meals.objects.get(slug=slug) obtiene el objeto Meals que tiene el slug proporcionado y lo asigna a la variable meal_detail.
Se crea un diccionario context que contiene los detalles de la comida obtenidos.
La función render() toma la solicitud (request), la plantilla 'Meals/detail.html', y el contexto (context) y renderiza la plantilla con el contexto proporcionado, devolviendo la página HTML resultante como respuesta.
"""

src/meals/templates/Meals/detail.html
{% extends 'base.html' %}
{% load static %}

{% block structure%}

<h1 class="logo me-auto menu section-bg" data-aos="zoom-in" data-aos-delay="100"><a href="{% url 'meals:meal_list' %}">Restaurantly</a></h1>
<div class=" section-bg " data-aos="zoom-in" data-aos-delay="100"> 
    <div class="text-center p-5">
        <a id="menu-link" href="{% url 'meals:meal_list' %}" class="nav-link scroll menu menu-link  btn btn-success">Menu</a>
    </div>
</div>
<div class="col-lg-12 mt-4 mt-lg-0 p-5 align-items-cente" data-aos="zoom-in" data-aos-delay="100">
    <div class="tab-content ">
        <div class="tab-pane active show" id="tab-1">
            <div class="row">
                <div class="col-lg-7 p-5"> <!-- Añadido: clase col-lg-8 para dar margen al contenido -->
                    <div class=" p-5"> <!-- Añadido: wrapper con padding -->
                        <h1>{{ meal_detail.name }}</h1>
                        <p class="fst-italic bi bi-check-circle"> {{ meal_detail.description }}</p>
                        <p class="fst-italic bi bi-check-circle">People: {{ meal_detail.people }}</p>
                        <p class=" fst-italic bi bi-check-circle">Preparation Time: {{ meal_detail.preperation_time }}</p>
                        <p> Price: ${{ meal_detail.price }}</p>
                    </div>
                </div>
                <div class="col-lg-4 text-center order-1 order-lg-2 about-img " data-aos="zoom-in" data-aos-delay="100">
                    <img src="{{ meal_detail.imagen.url }}" alt="" class="img-fluid">
                </div>
            </div>
        </div>
    </div>
</div>


{% endblock structure %}

src/meals/templates/Meals/list.html
{% extends 'base2.html' %}
{% load static %}
{% block body %}
<div class="container" data-aos="fade-up">
  <div class="section-title">
    <h2>Menu</h2>
    <p>Check Our Tasty Menu</p>
  </div>
  <div class="row" data-aos="fade-up" data-aos-delay="100">
    <div class="col-lg-12 d-flex justify-content-center">
      <ul id="menu-flters">
        {% for category in categories %}
          <li class="nav-item">
            <a class="nav-link" href="#{{ category }}" id="{{ category }}-tab" role="tab" aria-controls="{{ category }}" data-toggle="pill" aria-selected="true">{{ category }}</a>
          </li>
        {% endfor %}
      </ul>
    </div>
  </div>
  <div class="row menu-container" data-aos="fade-up" data-aos-delay="200">
    {% for category in categories %}
      <div class="tab-pane show active" id="{{ category }}" role="tabpanel" aria-labelledby="{{ category }}-tab">
        {% for meal in meal_list %}
          {% if meal.category == category %}  
            <div class="col-lg-6 menu-item filter-starters">
              <img src="{{ meal.imagen.url }}" class="menu-img" alt="">
              <div class="menu-content">
                <a href="{% url 'meals:meal_detail' meal.slug %}">{{ meal.name }}</a><span>${{ meal.price }}</span>
              </div>
              <div class="menu-ingredients">
                {{ meal.description }}
              </div>
            </div>
          {% endif %}
        {% endfor %}
      </div>
    {% endfor %}
  </div>
</div>
{% endblock body %}


<!--
  {% for meal in meal_list %} y {% endfor %}: Estas etiquetas de ciclo for se utilizan para iterar sobre 
  cada objeto meal en la lista meal_list. Por cada iteración del ciclo, se renderiza el contenido dentro 
  del bucle.
<div class="col-lg-6 menu-item filter-starters">: Este es el contenedor principal de cada elemento de 
  comida en la lista. La clase col-lg-6 define el ancho de la columna en diseños de tipo "grid", mientras 
  que menu-item y filter-starters son clases adicionales.
<img src="{{ meal.imagen.url }}" class="menu-img" alt="">: Esta etiqueta <img> muestra la imagen de la 
comida. El atributo src se establece en la URL de la imagen de la comida ({{ meal.imagen.url }}), que se 
obtiene del modelo de Django. El atributo class proporciona clases CSS adicionales para dar estilo a la 
imagen.
<a href="{% url 'meals:meal_detail' meal.slug %}">: Este es un enlace (<a>) que lleva al usuario a la 
  página de detalles de la comida. Utiliza la función  url  de Django para generar la URL de la 
  vista meal_detail en el espacio de nombres meals. El segundo argumento (meal.slug) proporciona el 
  valor del slug de la comida, que se utiliza como parte de la URL para identificar la comida específica.
-->

src/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta content="width=device-width, initial-scale=1.0" name="viewport">

  <!-- Favicons -->
  <link href="{% static 'site_static/img/favicon.png' %}" rel="icon">
  <link href="{% static 'site_static/img/apple-touch-icon.png' %}" rel="apple-touch-icon">

  <!-- Google Fonts -->
  <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Playfair+Display:ital,wght@0,400;0,500;0,600;0,700;1,400;1,500;1,600;1,700|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i" rel="stylesheet">

  <link href="{% static 'vendor/animate.css/animate.min.css' %}" rel="stylesheet">
  <link href="{% static 'vendor/aos/aos.css' %}" rel="stylesheet">
  <link href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
  <link href="{% static 'vendor/bootstrap-icons/bootstrap-icons.css' %}" rel="stylesheet">
  <link href="{% static 'vendor/boxicons/css/boxicons.min.css' %}" rel="stylesheet">
  <link href="{% static 'vendor/glightbox/css/glightbox.min.css' %}" rel="stylesheet">
  <link href="{% static 'vendor/swiper/swiper-bundle.min.css' %}" rel="stylesheet">


  <!-- Template Main CSS File -->
  <link href="{% static 'css/style.css' %}" rel="stylesheet">

  
</head>

<body>

  {% block structure%}

  {% endblock structure%}
  <!-- Vendor JS Files -->
  <script src="{% static 'vendor/aos/aos.js' %}"></script>
  <script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
  <script src="{% static 'vendor/glightbox/js/glightbox.min.js' %}"></script>
  <script src="{% static 'vendor/isotope-layout/isotope.pkgd.min.js' %}"></script>
  <script src="{% static 'vendor/swiper/swiper-bundle.min.js' %}"></script>
  <script src="{% static 'vendor/php-email-form/validate.js' %}"></script>

  <!-- Template Main JS File -->
  <script src="{% static 'js/main.js' %}"></script>

</body>

</html>